/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Components: typeof import('./src/components/index.vue')['default']
    CpNavBar: typeof import('./src/components/cp-nav-bar.vue')['default']
    CpRadioBtn: typeof import('./src/components/CpRadioBtn.vue')['default']
    Dialog: typeof import('./src/components/dialog.vue')['default']
    DialogPage: typeof import('./src/components/dialog/dialog-page.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    KnowledgeCard: typeof import('./src/components/knowledgeCard.vue')['default']
    KnowledgeList: typeof import('./src/components/knowledgeList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VanActionBar: typeof import('vant/es')['ActionBar']
    VanActionBarButton: typeof import('vant/es')['ActionBarButton']
    VanActionSheet: typeof import('vant/es')['ActionSheet']
    VanBadge: typeof import('vant/es')['Badge']
    VanButton: typeof import('vant/es')['Button']
    VanCell: typeof import('vant/es')['Cell']
    VanCellG: typeof import('vant/es')['CellG']
    VanCellGroup: typeof import('vant/es')['CellGroup']
    VanCheckbox: typeof import('vant/es')['Checkbox']
    VanCol: typeof import('vant/es')['Col']
    VanCountDown: typeof import('vant/es')['CountDown']
    VanDivider: typeof import('vant/es')['Divider']
    VanField: typeof import('vant/es')['Field']
    VanForm: typeof import('vant/es')['Form']
    VanIcon: typeof import('vant/es')['Icon']
    VanImage: typeof import('vant/es')['Image']
    VanList: typeof import('vant/es')['List']
    VanNavBar: typeof import('vant/es')['NavBar']
    VanPopup: typeof import('vant/es')['Popup']
    VanPullRefresh: typeof import('vant/es')['PullRefresh']
    VanRate: typeof import('vant/es')['Rate']
    VanRow: typeof import('vant/es')['Row']
    VanSearch: typeof import('vant/es')['Search']
    VanSidebar: typeof import('vant/es')['Sidebar']
    VanSidebarItem: typeof import('vant/es')['SidebarItem']
    VanSubmitBar: typeof import('vant/es')['SubmitBar']
    VanSwipe: typeof import('vant/es')['Swipe']
    VanSwipeItem: typeof import('vant/es')['SwipeItem']
    VanSwiper: typeof import('vant/es')['Swiper']
    VanSwiperItem: typeof import('vant/es')['SwiperItem']
    VanSwipItem: typeof import('vant/es')['SwipItem']
    VanTab: typeof import('vant/es')['Tab']
    VanTabbar: typeof import('vant/es')['Tabbar']
    VanTabbarItem: typeof import('vant/es')['TabbarItem']
    VanTabs: typeof import('vant/es')['Tabs']
    VanToast: typeof import('vant/es')['Toast']
    VanUploader: typeof import('vant/es')['Uploader']
  }
}
